from datetime import datetime

from reports.html_styles import get_styles

from reports.html_sections import (
    summary_section,
    failed_analysis_section,
    top_failed_section,
    suspicious_section,
    alerts_section,
    timeline_section,
    recommendation_section,
    ioc_section,
    threat_section,
)


def generate_html_report(results, output_file, threshold=5, top_n=5):

    generated_time = datetime.now().strftime("%d-%m-%Y %H:%M:%S")

    html = f"""
<!DOCTYPE html>

<html>

<head>

<meta charset="UTF-8">

<title>Digital Forensics Report</title>

{get_styles()}

</head>

<body>

<div class="container">

<div class="header">

<h1>🛡️ Digital Forensics Artifact Analyzer</h1>

<p>Automated Linux Authentication Log Investigation Report</p>

</div>

<div class="content">

<div class="metadata">

<p><strong>Generated:</strong> {generated_time}</p>

<p><strong>Failed Login Threshold:</strong> {threshold}</p>

<p><strong>Top Failed IPs Displayed:</strong> {top_n}</p>

</div>

{summary_section(results)}

{failed_analysis_section(results)}

{top_failed_section(results, top_n)}

{suspicious_section(results, threshold)}

{alerts_section(results)}

{timeline_section(results)}

{recommendation_section()}

{ioc_section(results)}

{threat_section(results)}

<div class="footer">

Generated by <strong>Digital Forensics Artifact Analyzer</strong>

</div>

</div>

</div>

</body>

</html>

"""

    with open(output_file, "w", encoding="utf-8") as file:
        file.write(html)

    print(f"HTML report generated successfully: {output_file}")