import os
from datetime import datetime
WIDTH = 80

#Report Printing
def print_report(results,threshold,top_n):
    WIDTH = 80

    print("=" * WIDTH)
    print("DIGITAL FORENSICS ARTIFACT ANALYZER".center(WIDTH))
    print("-" * WIDTH)
    print("Automated Authentication Log Investigation Report".center(WIDTH))
    print("=" * WIDTH)
    print()

    print()
    print("SUSPICIOUS FAILED LOGIN ANALYSIS :")
    print()

    print(f"{'IP Address':<20}{'Failed Attempts':<20}{'Unique Users':<20}{'Enumeration'}")
    print("-" * 75)
    
    for ip, count in results["failed_attempts"].items():
        unique_users = len(results["failed_users"][ip])
        Enumeration = "YES" if unique_users >= 3 else "NO"
        print(f"{ip:<20}{count:<20}{unique_users:<20}{Enumeration}")

    print("-" * 75)

    print()
    print("=" * 10, "LOG SUMMARY", "=" * 10)
    print()

    print("Total Lines :", results["total_lines"])
    print("Failed Logins :", results["total_failed"])
    print("Successful Logins :", results["total_successful"])
    print("Unique Failed IPs :", len(results["failed_attempts"]))

    print("\nTOP FAILED ATTEMPTS :")

    for ip, count in results["sorted_failed"][:top_n]:
        print(f"{ip:<20} -> {count}")
        
    print(f"\nSUSPICIOUS IPS : (>= {threshold} Attempts)")
    found = False
    for ip, count in results["sorted_failed"]:

        if count < threshold:
            break
        found = True
        print(f"{ip:<20} -> {count}")
    print()
    if not found:
      print("No suspicious IPs found.\n")

    print("="*38)
    print("POTENTIAL ACCOUNT COMPROMISE ALERTS ")
    print("="*38,"\n")
    print(f"{'IP Address':<20}{'User name':<20}{'Time Stamp'}")
    print("-" * 55)
    suspicious_found = False
    for alert in results["success_after_failure"]:
        suspicious_found = True
        print(f'{alert["ip"]:<20}{alert["username"]:<20}{alert["timestamp"]:<20}\n')
    if not suspicious_found:
        print("No alerts detected.\n")  
    
    
    print("\nRECENT EVENT TIMELINE : (Showing 5 latest events)")
    
    print("=" * 50)
    for event in results["event_timeline"][-5:]:
        print(
            f"{event['timestamp']} | "
            f"{event['status']:<15} | "
            f"{event['username']:<10} | "
            f"{event['ip']}"
            ) 
    print()
    print("="*30)
    print(" SECURITY ANALYST RECOMMENDATIONS ")
    print("="*30)
    print("• Investigate IPs exceeding the failed login threshold.")
    print("• Review accounts with successful logins after multiple failures.")
    print("• Enable Multi-Factor Authentication (MFA).")
    print("• Consider blocking repeated offending IP addresses.")

def save_report(results, filename, threshold=5, top_n=3):

    os.makedirs(os.path.dirname(filename), exist_ok=True)

    with open(filename, "w") as file:
        
        file.write("=" * WIDTH + "\n")
        file.write("DIGITAL FORENSICS ARTIFACT ANALYZER".center(WIDTH) + "\n")
        file.write("-" * WIDTH + "\n")
        file.write("Automated Authentication Log Investigation Report".center(WIDTH) + "\n")
        file.write("=" * WIDTH + "\n\n")

        file.write(f"{'Report Type':<15}: Authentication Log Analysis\n")
        file.write(f"{'Generated By':<15}: Digital Forensics Artifact Analyzer\n")
        file.write(f"{'Generated On':<15}: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n")
        file.write(f"{'Status':<15}: Completed\n")

        file.write("\n" + "=" * WIDTH + "\n\n")

        
        file.write("SUSPICIOUS FAILED LOGIN REPORT :\n\n")

        file.write(
            f"{'IP Address':<20}"
            f"{'Failed Attempts':<20}"
            f"{'Unique Users':<20}"
            f"{'Enumeration'}\n"
        )
        file.write("-" * 72 + "\n")

        for ip, count in results["failed_attempts"].items():
            unique_users = len(results["failed_users"][ip])
            enumeration = "YES" if unique_users >= 3 else "NO"

            file.write(
                f"{ip:<20}"
                f"{count:<20}"
                f"{unique_users:<20}"
                f"{enumeration}\n"
            )

        file.write("-" * 72 + "\n\n")

        file.write("=" * 10 + " LOG SUMMARY" + "=" * 10 + "\n\n")

        file.write(f"Total Lines : {results['total_lines']}\n")
        file.write(f"Failed Logins : {results['total_failed']}\n")
        file.write(f"Successful Logins : {results['total_successful']}\n")
        file.write(f"Unique Failed IPs : {len(results['failed_attempts'])}\n")

        file.write("\nTOP FAILED ATTEMPTS :\n")

        found = False
        for ip, count in results["sorted_failed"][:top_n]:
            file.write(f"{ip:<20} -> {count}\n")
            found = True

        if not found:
            file.write("No suspicious IPs found.\n")

        file.write(f"\nSUSPICIOUS IPS : (>= {threshold} Attempts)\n")

        found = False
        for ip, count in results["sorted_failed"]:

            if count < threshold:
                break

            found = True
            file.write(f"{ip:<20} -> {count}\n")

        if not found:
            file.write("No suspicious IPs found.\n")

        file.write("\n")
        file.write("=" * 38 + "\n")
        file.write("POTENTIAL ACCOUNT COMPROMISE ALERTS \n")
        file.write("=" * 38 + "\n\n")

        file.write(
            f"{'IP Address':<20}"
            f"{'User name':<20}"
            f"{'Time Stamp'}\n"
        )
        file.write("-" * 55 + "\n")

        suspicious_found = False

        for alert in results["success_after_failure"]:
            suspicious_found = True

            file.write(
                f"{alert['ip']:<20}"
                f"{alert['username']:<20}"
                f"{alert['timestamp']:<20}\n"
            )

        if not suspicious_found:
            file.write("No alerts detected.\n")

        file.write("\n")
        file.write("RECENT EVENT TIMELINE : (Showing 5 latest events)\n")
        file.write("=" * 45 + "\n")

        for event in results["event_timeline"][-5:]:
            file.write(
                f"{event['timestamp']} | "
                f"{event['status']:<15} | "
                f"{event['username']:<10} | "
                f"{event['ip']}\n"
            )

        file.write("\n")
        file.write("=" * 30 + "\n")
        file.write(" SECURITY ANALYST RECOMMENDATIONS \n")
        file.write("=" * 30 + "\n")

        file.write("• Investigate IPs exceeding the failed login threshold.\n")
        file.write("• Review accounts with successful logins after multiple failures.\n")
        file.write("• Enable Multi-Factor Authentication (MFA).\n")
        file.write("• Consider blocking repeated offending IP addresses.\n")
        file.write("\n")
        file.write("\n")
        file.write("=" * WIDTH + "\n")
        file.write("End of Investigation Report".center(WIDTH) + "\n")
        file.write("=" * WIDTH + "\n")
        